name: proyecto_financiero
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.2
  firebase_analytics: ^12.0.3
  flutter_native_splash: ^2.4.7

  # State management
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Utilities
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  uuid: ^4.3.3
  font_awesome_flutter: ^10.6.0
  fl_chart: ^0.66.0
  flutter_colorpicker: ^1.0.3

  # Local packages
  expense_repository:
    path: packages/expense_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner:
  firebase_auth_mocks: 0.15.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/icono.png
  android: true
  ios: true
